import '../models/post.dart';
import '../models/comment.dart';

class PostApi {
  static Future<List<PostItem>> getAllPosts() async {
    await Future.delayed(const Duration(milliseconds: 300));
    return List.from(_mockPosts);
  }

  static Future<PostItem?> getPostById(String id) async {
    await Future.delayed(const Duration(milliseconds: 100));
    try {
      return _mockPosts.firstWhere((p) => p.id == id);
    } catch (_) {
      return null;
    }
  }

  static Future<List<PostComment>> getCommentsForPost(String postId) async {
    await Future.delayed(const Duration(milliseconds: 200));
    return _mockComments.where((c) => c.postId == postId).toList();
  }

  static Future<PostComment> addComment(PostComment comment) async {
    await Future.delayed(const Duration(milliseconds: 200));
    _mockComments.add(comment);
    return comment;
  }

  static final List<PostItem> _mockPosts = [
    PostItem(
      id: 'p1',
      title: 'Sách Giải Tích 1 - Tái Bản 2024',
      content: 'Sách còn mới 95%, ít ghi chú. Bìa cứng, không rách. Phù hợp cho sinh viên năm 1-2. Giá rẻ hơn thị trường 40%. Liên hệ ngay!',
      category: 'Sách & Tài liệu',
      type: 'sell',
      price: '120.000đ',
      authorId: '2',
      authorName: 'Nguyễn Văn A',
      authorAvatar: 'https://i.pravatar.cc/150?img=2',
      images: [
        'https://picsum.photos/seed/book1a/800/600',
        'https://picsum.photos/seed/book1b/800/600',
        'https://picsum.photos/seed/book1c/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      likes: 24,
      views: 312,
      likedBy: ['3', '5', '7'],
      savedBy: ['4', '6'],
      condition: 'Như mới',
      location: 'Ký túc xá A',
      contact: '0912345678',
    ),
    PostItem(
      id: 'p2',
      title: 'Cần mua Laptop cũ i5 thế hệ 8 trở lên',
      content: 'Tìm mua laptop cũ, yêu cầu: i5 gen 8+, RAM 8GB, SSD 256GB. Giá 7-8 triệu. Máy còn đẹp, pin tốt.',
      category: 'Đồ điện tử',
      type: 'buy',
      price: '7.500.000đ',
      authorId: '3',
      authorName: 'Trần Thị B',
      authorAvatar: 'https://i.pravatar.cc/150?img=3',
      images: ['https://picsum.photos/seed/laptop1/800/600'],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      likes: 15,
      views: 203,
      likedBy: ['2', '4'],
      location: 'Khu B',
    ),
    PostItem(
      id: 'p3',
      title: 'Xe đạp thể thao Giant ATX 2024',
      content: 'Xe mới mua 3 tháng, còn bảo hành. Màu xanh đen, size M. Bán vì chuyển xe máy. Full phụ kiện: đèn, khóa, bình nước.',
      category: 'Xe đạp',
      type: 'sell',
      price: '4.200.000đ',
      authorId: '4',
      authorName: 'Lê Văn C',
      authorAvatar: 'https://i.pravatar.cc/150?img=4',
      images: [
        'https://picsum.photos/seed/bike1a/800/600',
        'https://picsum.photos/seed/bike1b/800/600',
        'https://picsum.photos/seed/bike1c/800/600',
        'https://picsum.photos/seed/bike1d/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(hours: 8)),
      likes: 42,
      views: 518,
      likedBy: ['2', '3', '5', '6', '8'],
      savedBy: ['7', '9', '10'],
      condition: 'Còn mới',
      location: 'Ký túc xá C',
      contact: '0923456789',
    ),
    PostItem(
      id: 'p4',
      title: 'Áo khoác hoodie unisex Hàn Quốc',
      content: 'Áo hoodie form rộng, màu đen trơn. Size L. Chất vải nỉ bông cao cấp, mặc rất ấm. Giặt đã 2-3 lần nhưng vẫn mới.',
      category: 'Quần áo',
      type: 'sell',
      price: '180.000đ',
      authorId: '5',
      authorName: 'Phạm Thị D',
      authorAvatar: 'https://i.pravatar.cc/150?img=5',
      images: [
        'https://picsum.photos/seed/hoodie1a/800/600',
        'https://picsum.photos/seed/hoodie1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(hours: 12)),
      likes: 31,
      views: 287,
      likedBy: ['2', '6', '8', '11'],
      condition: 'Đã sử dụng',
      location: 'Khu A',
    ),
    PostItem(
      id: 'p5',
      title: 'Bàn học gỗ có ngăn kéo',
      content: 'Bàn học gỗ tự nhiên, 1m2 x 60cm. Có 2 ngăn kéo. Màu nâu gỗ. Chắc chắn, không cong vênh. Bán vì sắp chuyển phòng.',
      category: 'Nội thất',
      type: 'sell',
      price: '850.000đ',
      authorId: '6',
      authorName: 'Hoàng Văn E',
      authorAvatar: 'https://i.pravatar.cc/150?img=6',
      images: [
        'https://picsum.photos/seed/desk1a/800/600',
        'https://picsum.photos/seed/desk1b/800/600',
        'https://picsum.photos/seed/desk1c/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(hours: 18)),
      likes: 28,
      views: 394,
      likedBy: ['3', '7', '9'],
      savedBy: ['4', '8'],
      condition: 'Tốt',
      location: 'Khu D',
      contact: '0934567890',
    ),
    PostItem(
      id: 'p6',
      title: 'Tai nghe Bluetooth Sony WH-1000XM4',
      content: 'Tai nghe chống ồn cao cấp. Mới 90%, hộp đầy đủ. Pin 8-10 giờ. Âm thanh tuyệt vời. Giá tốt hơn shop 30%.',
      category: 'Đồ điện tử',
      type: 'sell',
      price: '4.500.000đ',
      authorId: '7',
      authorName: 'Vũ Thị F',
      authorAvatar: 'https://i.pravatar.cc/150?img=7',
      images: [
        'https://picsum.photos/seed/headphone1a/800/600',
        'https://picsum.photos/seed/headphone1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      likes: 56,
      views: 672,
      likedBy: ['2', '3', '5', '8', '10', '12'],
      savedBy: ['4', '6', '9', '11'],
      condition: 'Như mới',
      location: 'Ký túc xá B',
    ),
    PostItem(
      id: 'p7',
      title: 'Cần mua sách Tiếng Anh chuyên ngành CNTT',
      content: 'Tìm mua sách Tiếng Anh chuyên ngành IT, bản photocopy cũng được. Giá phải chăng.',
      category: 'Sách & Tài liệu',
      type: 'buy',
      price: '50.000đ',
      authorId: '8',
      authorName: 'Đặng Văn G',
      authorAvatar: 'https://i.pravatar.cc/150?img=8',
      images: ['https://picsum.photos/seed/bookeng/800/600'],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      likes: 8,
      views: 145,
      likedBy: ['5'],
    ),
    PostItem(
      id: 'p8',
      title: 'Bộ đồ dùng học tập văn phòng phẩm',
      content: 'Bút bi, bút chì, tẩy, thước kẻ, bấm kim... Đầy đủ 20 món. Mới 100%, chưa bóc hộp. Giá cả bộ rẻ hơn lẻ.',
      category: 'Đồ dùng học tập',
      type: 'sell',
      price: '150.000đ',
      authorId: '9',
      authorName: 'Bùi Thị H',
      authorAvatar: 'https://i.pravatar.cc/150?img=9',
      images: [
        'https://picsum.photos/seed/stationery1a/800/600',
        'https://picsum.photos/seed/stationery1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 8)),
      likes: 19,
      views: 221,
      likedBy: ['2', '6', '10'],
      condition: 'Mới',
      location: 'Khu C',
    ),
    PostItem(
      id: 'p9',
      title: 'Quạt mini USB để bàn',
      content: 'Quạt mini USB, 3 cấp độ gió. Thiết kế nhỏ gọn, êm ái. Dùng được cho laptop, sạc dự phòng. Màu trắng.',
      category: 'Đồ điện tử',
      type: 'sell',
      price: '45.000đ',
      authorId: '10',
      authorName: 'Đinh Văn I',
      authorAvatar: 'https://i.pravatar.cc/150?img=10',
      images: ['https://picsum.photos/seed/fan1/800/600'],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      likes: 12,
      views: 178,
      likedBy: ['3', '7'],
      condition: 'Mới',
    ),
    PostItem(
      id: 'p10',
      title: 'Giày thể thao Nike Air Max',
      content: 'Giày Nike Air Max màu trắng đen. Size 42. Mới 85%, đi 5-6 lần. Đế còn rất tốt. Hộp, giấy đầy đủ.',
      category: 'Quần áo',
      type: 'sell',
      price: '1.200.000đ',
      authorId: '11',
      authorName: 'Dương Thị K',
      authorAvatar: 'https://i.pravatar.cc/150?img=11',
      images: [
        'https://picsum.photos/seed/shoe1a/800/600',
        'https://picsum.photos/seed/shoe1b/800/600',
        'https://picsum.photos/seed/shoe1c/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 5)),
      likes: 38,
      views: 456,
      likedBy: ['2', '4', '6', '8'],
      savedBy: ['5', '9'],
      condition: 'Tốt',
      location: 'Ký túc xá A',
    ),
    PostItem(
      id: 'p11',
      title: 'Vợt cầu lông Yonex Astrox 88D Pro',
      content: 'Vợt cầu lông chính hãng Yonex. Mới 90%. Đã căng dây Yonex BG80. Túi đựng, cán vợt dự phòng đầy đủ.',
      category: 'Thể thao',
      type: 'sell',
      price: '2.800.000đ',
      authorId: '12',
      authorName: 'Lý Văn L',
      authorAvatar: 'https://i.pravatar.cc/150?img=12',
      images: [
        'https://picsum.photos/seed/badminton1a/800/600',
        'https://picsum.photos/seed/badminton1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      likes: 27,
      views: 318,
      likedBy: ['3', '5', '11'],
      savedBy: ['7'],
      condition: 'Như mới',
      location: 'Khu B',
    ),
    PostItem(
      id: 'p12',
      title: 'Guitar Acoustic Yamaha F310',
      content: 'Guitar Yamaha F310 màu gỗ tự nhiên. Mới 80%, dây còn tốt. Âm thanh trong, phù hợp người mới học. Tặng kèm bao da.',
      category: 'Nhạc cụ',
      type: 'sell',
      price: '1.500.000đ',
      authorId: '13',
      authorName: 'Mai Thị M',
      authorAvatar: 'https://i.pravatar.cc/150?img=13',
      images: [
        'https://picsum.photos/seed/guitar1a/800/600',
        'https://picsum.photos/seed/guitar1b/800/600',
        'https://picsum.photos/seed/guitar1c/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 3, hours: 10)),
      likes: 45,
      views: 521,
      likedBy: ['2', '4', '6', '9', '12'],
      savedBy: ['5', '8', '10'],
      condition: 'Tốt',
      location: 'Khu D',
      contact: '0945678901',
    ),
    PostItem(
      id: 'p13',
      title: 'Cần mua điện thoại cũ giá rẻ',
      content: 'Tìm mua điện thoại cũ, chỉ cần nghe gọi nhắn tin. Pin tốt. Giá dưới 1 triệu.',
      category: 'Đồ điện tử',
      type: 'buy',
      price: '800.000đ',
      authorId: '14',
      authorName: 'Ngô Văn N',
      authorAvatar: 'https://i.pravatar.cc/150?img=14',
      images: ['https://picsum.photos/seed/phone1/800/600'],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 4)),
      likes: 6,
      views: 98,
      likedBy: ['7'],
    ),
    PostItem(
      id: 'p14',
      title: 'Balo Laptop Sakos 15.6 inch',
      content: 'Balo laptop chống nước, nhiều ngăn. Đựng được laptop 15.6". Màu đen. Còn mới 95%, dây đeo chắc chắn.',
      category: 'Phụ kiện',
      type: 'sell',
      price: '320.000đ',
      authorId: '15',
      authorName: 'Phan Thị O',
      authorAvatar: 'https://i.pravatar.cc/150?img=15',
      images: [
        'https://picsum.photos/seed/backpack1a/800/600',
        'https://picsum.photos/seed/backpack1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 4, hours: 6)),
      likes: 22,
      views: 267,
      likedBy: ['2', '5', '8'],
      savedBy: ['6'],
      condition: 'Như mới',
    ),
    PostItem(
      id: 'p15',
      title: 'Tủ nhựa 5 ngăn Duy Tân',
      content: 'Tủ nhựa 5 ngăn màu xanh dương. Còn mới, không bị nứt. Đựng quần áo, đồ dùng cá nhân rất tiện.',
      category: 'Nội thất',
      type: 'sell',
      price: '450.000đ',
      authorId: '2',
      authorName: 'Nguyễn Văn A',
      authorAvatar: 'https://i.pravatar.cc/150?img=2',
      images: [
        'https://picsum.photos/seed/cabinet1a/800/600',
        'https://picsum.photos/seed/cabinet1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 5)),
      likes: 17,
      views: 189,
      likedBy: ['4', '9'],
      condition: 'Tốt',
      location: 'Ký túc xá A',
    ),
    PostItem(
      id: 'p16',
      title: 'Sách lập trình Python căn bản',
      content: 'Sách học Python cho người mới bắt đầu. Có bài tập và lời giải chi tiết. Bìa mềm, 350 trang.',
      category: 'Sách & Tài liệu',
      type: 'sell',
      price: '95.000đ',
      authorId: '3',
      authorName: 'Trần Thị B',
      authorAvatar: 'https://i.pravatar.cc/150?img=3',
      images: [
        'https://picsum.photos/seed/python1a/800/600',
        'https://picsum.photos/seed/python1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 5, hours: 12)),
      likes: 33,
      views: 412,
      likedBy: ['2', '6', '10', '14'],
      savedBy: ['8', '12'],
      condition: 'Tốt',
    ),
    PostItem(
      id: 'p17',
      title: 'Đèn bàn học LED chống cận',
      content: 'Đèn LED bảo vệ mắt, 3 chế độ sáng. Có cổng USB sạc điện thoại. Thiết kế gập gọn. Màu trắng.',
      category: 'Đồ điện tử',
      type: 'sell',
      price: '210.000đ',
      authorId: '4',
      authorName: 'Lê Văn C',
      authorAvatar: 'https://i.pravatar.cc/150?img=4',
      images: ['https://picsum.photos/seed/lamp1/800/600'],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 6)),
      likes: 25,
      views: 298,
      likedBy: ['3', '7', '11'],
      condition: 'Mới',
      location: 'Ký túc xá C',
    ),
    PostItem(
      id: 'p18',
      title: 'Ghế gaming E-Dra Mars EGC203',
      content: 'Ghế gaming màu đen đỏ. Tựa lưng điều chỉnh, có gác chân. Ngồi rất êm. Bán vì chuyển phòng nhỏ hơn.',
      category: 'Nội thất',
      type: 'sell',
      price: '1.800.000đ',
      authorId: '5',
      authorName: 'Phạm Thị D',
      authorAvatar: 'https://i.pravatar.cc/150?img=5',
      images: [
        'https://picsum.photos/seed/chair1a/800/600',
        'https://picsum.photos/seed/chair1b/800/600',
        'https://picsum.photos/seed/chair1c/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 6, hours: 8)),
      likes: 51,
      views: 634,
      likedBy: ['2', '6', '8', '12', '15'],
      savedBy: ['4', '10', '13'],
      condition: 'Tốt',
      location: 'Khu A',
      contact: '0956789012',
    ),
    PostItem(
      id: 'p19',
      title: 'Áo thun basic nhiều màu',
      content: 'Set 5 áo thun trơn form rộng. Màu đen, trắng, xám, navy, be. Size M-L. Chất cotton 100%.',
      category: 'Quần áo',
      type: 'sell',
      price: '250.000đ',
      authorId: '6',
      authorName: 'Hoàng Văn E',
      authorAvatar: 'https://i.pravatar.cc/150?img=6',
      images: [
        'https://picsum.photos/seed/tshirt1a/800/600',
        'https://picsum.photos/seed/tshirt1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 7)),
      likes: 29,
      views: 356,
      likedBy: ['3', '9', '13'],
      condition: 'Mới',
    ),
    PostItem(
      id: 'p20',
      title: 'Bộ 3 nồi inox cao cấp',
      content: 'Nồi inox 304 size 16cm, 18cm, 20cm. Đáy 3 lớp, nấu nhanh chín đều. Nắp kính chịu nhiệt. Mới 100%.',
      category: 'Gia dụng',
      type: 'sell',
      price: '580.000đ',
      authorId: '7',
      authorName: 'Vũ Thị F',
      authorAvatar: 'https://i.pravatar.cc/150?img=7',
      images: [
        'https://picsum.photos/seed/pot1a/800/600',
        'https://picsum.photos/seed/pot1b/800/600',
        'https://picsum.photos/seed/pot1c/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 7, hours: 10)),
      likes: 34,
      views: 421,
      likedBy: ['5', '8', '11', '14'],
      savedBy: ['6', '9'],
      condition: 'Mới',
      location: 'Ký túc xá B',
    ),
    PostItem(
      id: 'p21',
      title: 'Cần mua máy tính bảng iPad cũ',
      content: 'Tìm mua iPad đời cũ, dùng học tập, ghi chú. Giá từ 3-5 triệu. Pin chai cũng được.',
      category: 'Đồ điện tử',
      type: 'buy',
      price: '4.000.000đ',
      authorId: '8',
      authorName: 'Đặng Văn G',
      authorAvatar: 'https://i.pravatar.cc/150?img=8',
      images: ['https://picsum.photos/seed/ipad1/800/600'],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 8)),
      likes: 11,
      views: 167,
      likedBy: ['4', '10'],
    ),
    PostItem(
      id: 'p22',
      title: 'Kệ sách 4 tầng gỗ MDF',
      content: 'Kệ sách 4 tầng, cao 120cm. Màu vân gỗ sồi. Lắp ráp dễ dàng. Chịu lực tốt, đựng được nhiều sách.',
      category: 'Nội thất',
      type: 'sell',
      price: '620.000đ',
      authorId: '9',
      authorName: 'Bùi Thị H',
      authorAvatar: 'https://i.pravatar.cc/150?img=9',
      images: [
        'https://picsum.photos/seed/shelf1a/800/600',
        'https://picsum.photos/seed/shelf1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 8, hours: 5)),
      likes: 21,
      views: 245,
      likedBy: ['2', '7', '12'],
      condition: 'Mới',
      location: 'Khu C',
    ),
    PostItem(
      id: 'p23',
      title: 'Chuột Gaming Logitech G102',
      content: 'Chuột gaming Logitech G102 Gen2. RGB 16.8 triệu màu. DPI 8000. Mới 90%, click nhẹ, không kêu.',
      category: 'Đồ điện tử',
      type: 'sell',
      price: '280.000đ',
      authorId: '10',
      authorName: 'Đinh Văn I',
      authorAvatar: 'https://i.pravatar.cc/150?img=10',
      images: [
        'https://picsum.photos/seed/mouse1a/800/600',
        'https://picsum.photos/seed/mouse1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 9)),
      likes: 37,
      views: 489,
      likedBy: ['3', '6', '9', '13'],
      savedBy: ['8'],
      condition: 'Như mới',
    ),
    PostItem(
      id: 'p24',
      title: 'Bàn phím cơ Keychron K2',
      content: 'Bàn phím cơ Keychron K2 RGB. Switch Gateron Brown. Kết nối Bluetooth + USB. Hot-swap. Keycap PBT.',
      category: 'Đồ điện tử',
      type: 'sell',
      price: '1.650.000đ',
      authorId: '11',
      authorName: 'Dương Thị K',
      authorAvatar: 'https://i.pravatar.cc/150?img=11',
      images: [
        'https://picsum.photos/seed/keyboard1a/800/600',
        'https://picsum.photos/seed/keyboard1b/800/600',
        'https://picsum.photos/seed/keyboard1c/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 9, hours: 12)),
      likes: 62,
      views: 784,
      likedBy: ['2', '5', '7', '10', '14', '15'],
      savedBy: ['4', '8', '12'],
      condition: 'Như mới',
      location: 'Ký túc xá A',
      contact: '0967890123',
    ),
    PostItem(
      id: 'p25',
      title: 'Túi xách nữ da PU cao cấp',
      content: 'Túi xách tay nữ màu đen. Da PU mềm mịn. Nhiều ngăn tiện lợi. Phù hợp đi học, đi làm.',
      category: 'Phụ kiện',
      type: 'sell',
      price: '290.000đ',
      authorId: '12',
      authorName: 'Lý Văn L',
      authorAvatar: 'https://i.pravatar.cc/150?img=12',
      images: [
        'https://picsum.photos/seed/bag1a/800/600',
        'https://picsum.photos/seed/bag1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 10)),
      likes: 26,
      views: 312,
      likedBy: ['5', '9', '13'],
      condition: 'Mới',
    ),
    PostItem(
      id: 'p26',
      title: 'Máy sấy tóc Panasonic 2000W',
      content: 'Máy sấy tóc công suất lớn. 3 chế độ nhiệt độ. Động cơ bền. Sấy nhanh khô, không hư tóc.',
      category: 'Gia dụng',
      type: 'sell',
      price: '380.000đ',
      authorId: '13',
      authorName: 'Mai Thị M',
      authorAvatar: 'https://i.pravatar.cc/150?img=13',
      images: ['https://picsum.photos/seed/dryer1/800/600'],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 10, hours: 8)),
      likes: 18,
      views: 223,
      likedBy: ['6', '11'],
      condition: 'Tốt',
      location: 'Khu D',
    ),
    PostItem(
      id: 'p27',
      title: 'Giày sandal nữ quai ngang',
      content: 'Sandal nữ đế bệt màu kem. Size 37. Mới 100%, chưa đi. Thiết kế tối giản, dễ phối đồ.',
      category: 'Quần áo',
      type: 'sell',
      price: '165.000đ',
      authorId: '14',
      authorName: 'Ngô Văn N',
      authorAvatar: 'https://i.pravatar.cc/150?img=14',
      images: [
        'https://picsum.photos/seed/sandal1a/800/600',
        'https://picsum.photos/seed/sandal1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 11)),
      likes: 14,
      views: 176,
      likedBy: ['3', '8'],
      condition: 'Mới',
    ),
    PostItem(
      id: 'p28',
      title: 'Bóng đá size 5 Molten',
      content: 'Bóng đá Molten FIFA Quality. Da PU. Độ nảy tốt. Dùng được sân cỏ nhân tạo và tự nhiên.',
      category: 'Thể thao',
      type: 'sell',
      price: '420.000đ',
      authorId: '15',
      authorName: 'Phan Thị O',
      authorAvatar: 'https://i.pravatar.cc/150?img=15',
      images: [
        'https://picsum.photos/seed/ball1a/800/600',
        'https://picsum.photos/seed/ball1b/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 11, hours: 6)),
      likes: 23,
      views: 267,
      likedBy: ['4', '7', '12'],
      condition: 'Mới',
      location: 'Ký túc xá C',
    ),
    PostItem(
      id: 'p29',
      title: 'Sách Toán Cao Cấp A1 A2 A3',
      content: 'Bộ 3 cuốn Toán Cao Cấp của GS. Trần Đức Long. In năm 2023. Ghi chú ít, còn rất đẹp.',
      category: 'Sách & Tài liệu',
      type: 'sell',
      price: '285.000đ',
      authorId: '2',
      authorName: 'Nguyễn Văn A',
      authorAvatar: 'https://i.pravatar.cc/150?img=2',
      images: [
        'https://picsum.photos/seed/mathbook1a/800/600',
        'https://picsum.photos/seed/mathbook1b/800/600',
        'https://picsum.photos/seed/mathbook1c/800/600',
      ],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 12)),
      likes: 41,
      views: 512,
      likedBy: ['3', '5', '9', '14'],
      savedBy: ['7', '11'],
      condition: 'Như mới',
      location: 'Ký túc xá A',
      contact: '0912345678',
    ),
    PostItem(
      id: 'p30',
      title: 'Cần mua xe đạp điện cũ',
      content: 'Tìm mua xe đạp điện cũ, pin còn tốt. Giá từ 4-6 triệu. Ưu tiên khu vực Ký túc xá.',
      category: 'Xe đạp',
      type: 'buy',
      price: '5.000.000đ',
      authorId: '3',
      authorName: 'Trần Thị B',
      authorAvatar: 'https://i.pravatar.cc/150?img=3',
      images: ['https://picsum.photos/seed/ebike1/800/600'],
      status: 'approved',
      timestamp: DateTime.now().subtract(const Duration(days: 12, hours: 10)),
      likes: 9,
      views: 142,
      likedBy: ['6'],
      location: 'Khu B',
    ),
  ];

  static final List<PostComment> _mockComments = [
    PostComment(
      id: 'c1',
      postId: 'p1',
      authorId: '4',
      authorName: 'Lê Văn C',
      content: 'Sách còn mới không bạn? Có thể xem trước không?',
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
      authorAvatar: 'https://i.pravatar.cc/150?img=4',
    ),
    PostComment(
      id: 'c2',
      postId: 'p1',
      authorId: '2',
      authorName: 'Nguyễn Văn A',
      content: 'Còn mới 95% bạn nhé. Bạn qua ký túc xá A xem được.',
      createdAt: DateTime.now().subtract(const Duration(minutes: 45)),
      authorAvatar: 'https://i.pravatar.cc/150?img=2',
    ),
    PostComment(
      id: 'c3',
      postId: 'p1',
      authorId: '7',
      authorName: 'Vũ Thị F',
      content: 'Giá có thương lượng được không ạ?',
      createdAt: DateTime.now().subtract(const Duration(minutes: 20)),
      authorAvatar: 'https://i.pravatar.cc/150?img=7',
    ),
    PostComment(
      id: 'c4',
      postId: 'p3',
      authorId: '8',
      authorName: 'Đặng Văn G',
      content: 'Xe đẹp quá! Còn bảo hành đến khi nào vậy bạn?',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      authorAvatar: 'https://i.pravatar.cc/150?img=8',
    ),
    PostComment(
      id: 'c5',
      postId: 'p3',
      authorId: '4',
      authorName: 'Lê Văn C',
      content: 'Còn bảo hành 9 tháng nữa nhé bạn. Hóa đơn đầy đủ.',
      createdAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 30)),
      authorAvatar: 'https://i.pravatar.cc/150?img=4',
    ),
    PostComment(
      id: 'c6',
      postId: 'p6',
      authorId: '12',
      authorName: 'Lý Văn L',
      content: 'Tai nghe này pin lâu thật không bạn? Tôi định mua.',
      createdAt: DateTime.now().subtract(const Duration(hours: 10)),
      authorAvatar: 'https://i.pravatar.cc/150?img=12',
    ),
    PostComment(
      id: 'c7',
      postId: 'p6',
      authorId: '7',
      authorName: 'Vũ Thị F',
      content: 'Pin rất lâu, tôi dùng cả ngày không lo hết. Chống ồn cũng rất tốt!',
      createdAt: DateTime.now().subtract(const Duration(hours: 9)),
      authorAvatar: 'https://i.pravatar.cc/150?img=7',
    ),
    PostComment(
      id: 'c8',
      postId: 'p12',
      authorId: '5',
      authorName: 'Phạm Thị D',
      content: 'Guitar âm thanh thế nào? Có dạy chơi không bạn?',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      authorAvatar: 'https://i.pravatar.cc/150?img=5',
    ),
    PostComment(
      id: 'c9',
      postId: 'p18',
      authorId: '10',
      authorName: 'Đinh Văn I',
      content: 'Ghế này ngồi có êm không? Giá còn bớt được không ạ?',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      authorAvatar: 'https://i.pravatar.cc/150?img=10',
    ),
    PostComment(
      id: 'c10',
      postId: 'p24',
      authorId: '14',
      authorName: 'Ngô Văn N',
      content: 'Bàn phím này hot-swap quá xịn! Mình đang tìm mua.',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      authorAvatar: 'https://i.pravatar.cc/150?img=14',
    ),
  ];
}
